
//route handler to init the google OAuth via set URI
module.exports = (app) => {
    app.get(
        '/auth/google', passport.authenticate('google', {
        //info being requested from google api
        scope: ['profile', 'email']
    } ))

// google strategy called to access the code generated by authentication 

app.get('/auth/google/callback', passport.authenticate('google'))
}
