//Not using ES2015 syntax, JS module syntax
const express = require('express');
const passport = require('passport');
const GoogleStrategy = require('passport-google-oauth20');
const keys = require('./config/keys')

//declaration of express app
const app = express();


// init route handler

// '/' is the route portion of the handler


//app.get('/', (req, res) => {
//    res.send({ hi : 'sup'})

//})


/**
 * call the passport module and initialize google strategy from passport
 */
passport.use(
    new GoogleStrategy(
    {
        clientID: keys.googleClientID,
        clientSecret: keys.googleClientSecret,
        callbackURL: '/auth/google/callback'
    }, accessToken => {
        console.log(accessToken)
        }
    )
);
//route handler to init the google OAuth via set URI
app.get(
    '/auth/google', passport.authenticate('google', {
        //info being requested from google api
        scope: ['profile', 'email']
    } ))

// google strategy called to access the code generated by authentication 

app.get('/auth/google/callback', passport.authenticate('google'))

// express executes node to listen port 5000

// dynamically set port, heroku insert env variables to execute code in the node compilation or default to 5000
const PORT = process.env.PORT || 5000

app.listen(PORT);